# Generated by Django 3.0.2 on 2020-06-05 15:36

import Post.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20200605_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/files', validators=[Post.validator.validate_file_extension]),
        ),
    ]
