# Generated by Django 3.0.2 on 2020-06-05 15:40

import Post.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_auto_20200605_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.ImageField(upload_to='uploads', validators=[Post.validator.validate_image]),
        ),
    ]
