# Generated by Django 3.0.2 on 2020-01-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20200115_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(default=False, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
