# Generated by Django 3.0.2 on 2020-06-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20200605_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='title',
        ),
    ]
