# Generated by Django 3.0.2 on 2020-01-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_auto_20200116_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('createdAt', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('replay', models.TextField(max_length=200)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='Post.Comment')),
            ],
        ),
    ]
