# Generated by Django 3.0.2 on 2020-01-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_auto_20200116_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Post.Comment'),
        ),
        migrations.DeleteModel(
            name='Replay',
        ),
    ]
