# Generated by Django 3.0.2 on 2020-01-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_auto_20200116_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
