# Generated by Django 3.0.2 on 2020-01-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0014_auto_20200120_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=3),
        ),
    ]
