# Generated by Django 3.0.2 on 2020-01-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0015_auto_20200123_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.DecimalField(blank=True, decimal_places=False, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.DecimalField(blank=True, decimal_places=False, default=0, max_digits=3),
        ),
    ]
